---

- hosts: all
  become: yes
  pre_tasks:

  - name: update & upgrade server
    apt: 
      update_cache: yes
      upgrade: yes

  - name: set cron job to check uptime of the server every 12 am
    cron:
      name: set cron job to check uptime of the server every 12 am
      minute: "0"
      hour: "0"
      day: "*"
      month: "*"
      weekday: "*"
      job: "/usr/bin/uptime > /var/log/uptime_check.log 2>&1"
      state: present

  - name: copy the bash script to slave machine
    copy:
      src: deploy-lamp-slave.sh
      dest: ~/
      owner: root
      group: root
      mode: 0744

  - name: Set Execute Permissions on the Script
    command: chmod +x ~/deploy-lamp-slave.sh

  - name: Run Bash Script
    # command: sudo ./deploy-lamp-slave.sh joyjoel joyjoel@123 < /dev/null
    command: bash ~/deploy-lamp-slave.sh joyjoel joyjoel@123 < /dev/null

  - name: Verify PHP application accessibility
    uri:
      # url: "http://{{ ansible_host }}/index.php"  # Replace index.php with the correct URL of your PHP application
      url: "http://192.168.33.30"  # http://192.168.33.30/
      status_code: 200
    register: php_app_check